---
swagger: "2.0"
info:
  version: "1.0"
  title: Data Service Core API
host: go.dev.centime.com
basePath: /core/1.0/
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /user/{userId}:
    get:
      summary: Fetch User by Id
      parameters:
      - name: userId
        in: path
        required: true
        type: integer
      responses:
        "200":
          description: Response for the GET request
          schema:
            $ref: '#/definitions/inline_response_200'
        default:
          description: Generic Error Response
          schema:
            $ref: '#/definitions/Error Response'
          x-oad-type: response
    put:
      summary: Update User by Id
      parameters:
      - name: userId
        in: path
        required: true
        type: integer
      - in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        "200":
          description: Success or Partial Success Response for Put/Post methods
          schema:
            $ref: '#/definitions/inline_response_200_1'
        default:
          description: Generic Error Response
          schema:
            $ref: '#/definitions/Error Response'
          x-oad-type: response
    delete:
      summary: Delete User by Id
      parameters:
      - name: userId
        in: path
        required: true
        type: integer
      responses:
        "200":
          description: Delete Success Response
          schema:
            $ref: '#/definitions/inline_response_200_2'
        default:
          description: Generic Error Response
          schema:
            $ref: '#/definitions/Error Response'
          x-oad-type: response
  /users:
    get:
      summary: Fetch Users by clientId and dynamic filters
      parameters:
      - name: clientId
        in: query
        required: true
        type: integer
      - name: filter
        in: query
        required: false
        type: string
      - name: start
        in: query
        required: false
        type: integer
      - name: limit
        in: query
        required: false
        type: integer
      responses:
        "200":
          description: Response for the GET request
          schema:
            $ref: '#/definitions/inline_response_200'
        default:
          description: Generic Error Response
          schema:
            $ref: '#/definitions/Error Response'
          x-oad-type: response
    post:
      summary: Create Users for a ClientID
      parameters:
      - name: clientId
        in: query
        required: true
        type: integer
      - in: body
        name: users
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/User'
      responses:
        "200":
          description: Success or Partial Success Response for Put/Post methods
          schema:
            $ref: '#/definitions/inline_response_200_1'
        default:
          description: Generic Error Response
          schema:
            $ref: '#/definitions/Error Response'
          x-oad-type: response
definitions:
  error:
    type: object
    properties:
      code:
        type: string
      detail:
        type: string
  fault:
    type: object
    properties:
      code:
        type: string
      detail:
        type: string
    title: Non fatal errors
  faults:
    type: array
    items:
      $ref: '#/definitions/fault'
  User:
    type: object
    properties:
      LoginID:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      primaryEmail:
        type: string
      primaryMobile:
        type: string
      DisplayName:
        type: string
      addressId:
        type: integer
  inline_response_200:
    type: object
    properties:
      status:
        type: string
        default: SUCCESS
        enum:
        - SUCCESS
        x-oad-type: string
      results:
        type: array
        items:
          $ref: '#/definitions/User'
  Error Response:
    type: object
    properties:
      status:
        type: string
        default: FAILED
        enum:
        - FAILED
      error:
        $ref: '#/definitions/error'
  inline_response_200_1:
    type: object
    properties:
      status:
        type: string
        default: SUCCESS
        enum:
        - SUCCESS
        - PARTIAL_SUCCESS
        x-oad-type: string
      faults:
        $ref: '#/definitions/faults'
  inline_response_200_2:
    type: object
    properties:
      status:
        type: string
        default: SUCCESS
        enum:
        - SUCCESS
        x-oad-type: string
responses:
  GETResponse:
    description: Response for the GET request
    schema:
      $ref: '#/definitions/inline_response_200'
  PutPostResponse:
    description: Success or Partial Success Response for Put/Post methods
    schema:
      $ref: '#/definitions/inline_response_200_1'
  DeleteResponse:
    description: Delete Success Response
    schema:
      $ref: '#/definitions/inline_response_200_2'
  ErrorResponse:
    description: Generic Error Response
    schema:
      $ref: '#/definitions/Error Response'
    x-oad-type: response
